### ISSUE TITLE
Suggest two modules be submodules

### ISSUE THREAD

**Issue by dueyfinster** [paruss/AmIDiversified#2]
From looking at the structure, it looks like two repos were combined in to one.  Suggest to either make one repo or split in to two and use git submodules:
https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by paruss** [comment]
I dont see what you mean, only created 1 repo and added my two artifacts to it?

**Comment by dueyfinster** [comment]
there's two .gitignore's in each module, looks to me as if they were split out

**Comment by paruss** [comment]
Ah see what you mean, there are two, not sure why, ill just  delete them.
